#include "Card.hpp"
#include "Deck.hpp"
#include "Diamond.hpp"
#include "Spade.hpp"
#include "Club.hpp"
#include "Heart.hpp"
#include "Menu.hpp"
#include "Test.hpp"


int main()
{
    std::srand((unsigned int)std::time(nullptr));
    Deck cardDeck1;
    Test test1;
    cardDeck1.printDeck();
    std::cout << "--------------------------------------------- Shuffling Deck ------------------------------------------------" << std::endl;
    cardDeck1.shuffleDeck();
    cardDeck1.printShuffledDeck();
    test1.test_all();
    int exit = 0;
    sf::RenderWindow window(sf::VideoMode({ 1920, 1080 }), "Scoundrel");
    sf::CircleShape shape(100.f);
    shape.setFillColor(sf::Color::Green);

    // Tester code for button
    sf::Texture startButtonTexture;
    sf::Texture infoButtonTexture;
    sf::Texture exitButtonTexture;
    sf::Texture cardslot;
    sf::Texture runbutton;
    sf::Texture fistbtn;
    sf::Texture weaponbtn;

    //Load Sprites
    sf::Texture losescreen;
    losescreen.loadFromFile("Lost_Screen.png");
    sf::Sprite lost(losescreen);

    sf::Texture winscreen;
    winscreen.loadFromFile("Win_Screen.png");
    sf::Sprite win(winscreen);


    startButtonTexture.loadFromFile("StartButton.png"); //Note that buttons that look good were generated by Chat GBT
    infoButtonTexture.loadFromFile("info_button.png");
    exitButtonTexture.loadFromFile("Quit.png");
    cardslot.loadFromFile("Clear_Space.png");
    runbutton.loadFromFile("Run_Button.png");
    fistbtn.loadFromFile("Fist_Button.png");
    weaponbtn.loadFromFile("Weapon_Button.png");
    Menu runit(startButtonTexture, infoButtonTexture, exitButtonTexture, cardslot,runbutton, lost, win, fistbtn, weaponbtn);

 /*   startButtonTexture.loadFromFile("StartButton.png");
    ScreenButton startButton(startButtonTexture);
    startButton.getSprite().setPosition(sf::Vector2f(1920 / 2 - 150, 500));
    startButton.activate();*/



    sf::Texture bgTexture;
    bgTexture.loadFromFile("background.jpg");
    sf::Sprite bgSprite(bgTexture); //Background Sprite


    sf::Vector2f Position1 = { ((1920 / 2) - 500) - 100, 200 };
    sf::Vector2f Position2 = { ((1920 / 2) - 160) - 100, 200 };
    sf::Vector2f Position3 = { ((1920 / 2) + 160) - 100, 200 };
    sf::Vector2f Position4 = { ((1920 / 2) + 500) - 100, 200 };
    sf::Vector2f UserCard = { (1920 / 2) - 100, 700 };
    sf::Vector2f UserStack = { (1920 / 2) - 50, 725 };



    bgSprite.setScale(sf::Vector2f(window.getSize().x / 100, window.getSize().y / 100));

    while (window.isOpen() && exit == 0)
    {
        while (const std::optional event = window.pollEvent())
        {
            if (event->is<sf::Event::Closed>())
                window.close();
        }

        window.clear();
        window.draw(bgSprite); //Draw background

        exit = runit.updatestate(window, cardDeck1);
        window.display();
    }
}